const GameCommandTypes = Object.freeze({
    BEGIN_GAME: "BEGIN_GAME",
    MULLIGAN: "MULLIGAN",
    ADVANCE_PHASE: "ADVANCE_PHASE",
    PLAY_CARD: "PLAY_CARD",
    PLAY_GROWTH_CARD: "PLAY_GROWTH_CARD",
    ACTIVATE_CARD: "ACTIVATE_CARD",
    ACTIVATE_ADVENTURE_CARD: "ACTIVATE_ADVENTURE_CARD",
    DECLARE_QUEST_PARTICIPATION:
        "DECLARE_QUEST_PARTICIPATION",
    COMPLETE_QUEST_PARTICIPATION:
        "COMPLETE_QUEST_PARTICIPATION",
    START_QUEST_PREPARATION: "START_QUEST_PREPARATION",
    PASS_QUEST_PREPARATION: "PASS_QUEST_PREPARATION",
    RESOLVE_QUEST: "RESOLVE_QUEST",
    RESOLVE_SELECTION: "RESOLVE_SELECTION"
});

export default GameCommandTypes;
